"""Canonical runtime CLI for the agents-governance package.

Each verb delegates to a real owner inside the package or its declared
tools. No argparse/click/rich/typer — pure ``sys`` + ``importlib``.
"""

from __future__ import annotations

import importlib
import sys
from pathlib import Path

from .bundle import GovernanceBundle
from .capsule import render_capsule
from .projection import HOOKS, _manifest_path
from .provenance import version as distribution_version
from .rules import prompt_defense_body

_VERBS = ("help", "doctor", "check", "sync", "evaluate", "secure", "clean", "live")

USAGE = """\
Usage: agentsctl <verb> [options]

Verbs:
  help      Show help and supported verbs.
  doctor    Load the governance bundle and report diagnostics.
  check     Validate the bundle against config/workspace.yaml storage rules.
  sync      Project the capsule into provider hook surfaces (fixed-point).
  evaluate  Run every skill eval file under config/evals/ and report.
  secure    Verify the security triage contract is in place.
  clean     Remove every file marked as governed/generated by the bundle.
  live      Print runtime provenance (version, git-sha, capsule digest).
"""

_NO_PROJECT = "agentsctl must be run from the agents-governance project root"

_PROMPT_DEFENSE_IDENTITY = "security/prompt-defense"


def main(argv: list[str] | None = None) -> int:
    """Entry-point body used by the ``agentsctl`` console script."""

    args = argv if argv is not None else sys.argv[1:]
    verb = args[0] if args else "help"

    if verb not in _VERBS:
        print(f"error: unknown verb {verb!r}", file=sys.stderr)
        print(USAGE, file=sys.stderr)
        return 2

    if verb == "help":
        return _help(args[1:])

    root = _project_root()
    if root is None:
        print(_NO_PROJECT, file=sys.stderr)
        return 1

    if verb == "doctor":
        return _doctor(root, args[1:])
    if verb == "check":
        return _check(root, args[1:])
    if verb == "sync":
        return _sync(root, args[1:])
    if verb == "evaluate":
        return _evaluate(root, args[1:])
    if verb == "secure":
        return _secure(root, args[1:])
    if verb == "clean":
        return _clean(root, args[1:])
    if verb == "live":
        return _live(root, args[1:])

    return 0


def _project_root() -> Path | None:
    marker = Path("pyproject.toml")
    cwd = Path.cwd()
    for candidate in (cwd, *cwd.parents):
        if (candidate / marker).is_file() and "agents-governance" in (
            (candidate / marker).read_text(encoding="utf-8")
        ):
            return candidate
    maybe = Path(__file__).resolve().parent.parent
    if (maybe / marker).is_file():
        return maybe
    return None


def _help(args: list[str]) -> int:
    print(USAGE, end="")
    if args:
        print(f"\n(help takes no arguments, got {args!r})", file=sys.stderr)
        return 2
    return 0


def _load_bundle(root: Path) -> GovernanceBundle:
    return GovernanceBundle.load(root)


def _doctor(root: Path, args: list[str]) -> int:
    if args:
        print(f"doctor takes no arguments, got {args!r}", file=sys.stderr)
        return 2
    bundle = _load_bundle(root)
    capsule = render_capsule(bundle)
    print(
        f"Bundle: schema={bundle.schema_version} distribution={bundle.distribution_version}"
    )
    print(f"  rules: {len(bundle.rules)}")
    print(f"  skills: {len(bundle.skills)}")
    print(f"  commands: {len(bundle.commands)}")
    print(f"  agents: {len(bundle.agents)}")
    print(f"  hook surfaces: {len(HOOKS)}")
    print(f"  capsule digest: {capsule.digest}")
    return 0


def _check(root: Path, args: list[str]) -> int:
    if args:
        print(f"check takes no arguments, got {args!r}", file=sys.stderr)
        return 2
    bundle = _load_bundle(root)
    workspace_path = root / "config" / "workspace.yaml"
    if not workspace_path.is_file():
        print(f"error: workspace config not found: {workspace_path}", file=sys.stderr)
        return 1
    import yaml

    workspace = yaml.safe_load(workspace_path.read_text(encoding="utf-8"))
    storage_count = len(workspace) if isinstance(workspace, dict) else 0
    print(
        f"Bundle: schema={bundle.schema_version} distribution={bundle.distribution_version}"
    )
    print(f"Workspace config: {workspace_path} ({storage_count} storage entries)")
    print(f"Hook surfaces: {len(HOOKS)} (fixed-point validated by sync)")
    return 0


def _sync(root: Path, args: list[str]) -> int:
    if args:
        print(f"sync takes no arguments, got {args!r}", file=sys.stderr)
        return 2
    bundle = _load_bundle(root)
    from .projection import project_from_bundle

    project_from_bundle(root, bundle)
    return 0


def _evaluate(root: Path, args: list[str]) -> int:
    if args:
        print(f"evaluate takes no arguments, got {args!r}", file=sys.stderr)
        return 2
    audit = importlib.import_module("agents_governance.skill_evals")
    bundle = _load_bundle(root)
    policy = audit.audit_skill_evals(root, bundle.skills)
    print(
        f"Skill evals audited: {len(bundle.skills)} suites (policy v{policy.version})"
    )
    print(f"  default_suite_version: {policy.default_suite_version}")
    print(f"  task glob: {policy.task_glob}")
    return 0


def _secure(root: Path, args: list[str]) -> int:
    if args:
        print(f"secure takes no arguments, got {args!r}", file=sys.stderr)
        return 2
    bundle = _load_bundle(root)
    security_rules = [r for r in bundle.rules if r.category == "security"]
    print(f"Security rules: {len(security_rules)}")
    try:
        body = prompt_defense_body(bundle.rules)
        print(f"  prompt-defense: present ({len(body)} chars)")
    except ValueError as exc:
        print(f"  prompt-defense: MISSING ({exc})", file=sys.stderr)
        return 1
    print("Security triage contract: in place (see docs/security/security-triage.md)")
    return 0


def _clean(root: Path, args: list[str]) -> int:
    if args:
        print(f"clean takes no arguments, got {args!r}", file=sys.stderr)
        return 2
    removed = 0
    for hook in HOOKS:
        manifest = root / _manifest_path(hook.provider)
        if manifest.is_file():
            manifest.unlink()
            removed += 1
    opcode_plugin = root / ".opencode" / "plugins" / "aihub-governance.ts"
    if opcode_plugin.is_file():
        opcode_plugin.unlink()
        removed += 1
    opcode_manifest = (
        root / ".opencode" / "plugins" / ".aihub-governance.ts.agents-governance.json"
    )
    if opcode_manifest.is_file():
        opcode_manifest.unlink()
        removed += 1
    for name in ("CLAUDE.md", "GEMINI.md"):
        path = root / name
        if path.is_file() and "AIHUB-INSTRUCTION-POINTER" in path.read_text(
            encoding="utf-8"
        ):
            path.unlink()
            removed += 1
    print(f"Removed {removed} managed manifests and generated files")
    return 0


def _live(root: Path, args: list[str]) -> int:
    if args:
        print(f"live takes no arguments, got {args!r}", file=sys.stderr)
        return 2
    bundle = _load_bundle(root)
    capsule = render_capsule(bundle)
    print("package: agents-governance")
    print(f"version: {distribution_version()}")
    print(f"schema: {bundle.schema_version}")
    print(f"capsule digest: {capsule.digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
