"""Canonical model-pipeline contract and generated repository projections."""

from __future__ import annotations

import http.client
import json
import os
import urllib.parse
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

_OPENAI_SKILL_FIELDS = frozenset({"interface", "dependencies", "policy"})


@dataclass(frozen=True)
class PipelineFinding:
    """One generated surface that differs from the pipeline owner."""

    path: Path
    message: str


def resolve(root: Path) -> str:
    """Resolve the stable alias from the repository-owned SSOT."""

    path = root / "config" / "model-pipeline.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload != {"pipeline": "ai-hub-primary", "version": 1}:
        raise ValueError(f"{path}: expected the version 1 ai-hub-primary contract")
    return "ai-hub-primary"


def _yaml_model(path: Path) -> str | None:
    payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    config = payload.get("config") if isinstance(payload, dict) else None
    if path.name == ".waza.yaml":
        config = payload.get("defaults") if isinstance(payload, dict) else None
    model = config.get("model") if isinstance(config, dict) else None
    return model if isinstance(model, str) else None


def _agent_model(path: Path) -> str | None:
    for line in path.read_text(encoding="utf-8").splitlines()[:12]:
        if line.startswith("model:"):
            return line.partition(":")[2].strip()
    return None


def projection_paths(root: Path) -> list[Path]:
    """Return every surface whose model field is generated by this owner."""

    return [
        root / ".waza.yaml",
        root / "config" / "waza" / "preflight" / "eval.yaml",
        *sorted((root / "evals").glob("*/eval.yaml")),
        *sorted((root / "agents").glob("*.md")),
        root / "agents" / "manifest.json",
    ]


def findings(root: Path) -> list[PipelineFinding]:
    """Return projection and unsupported-metadata drift."""

    expected = resolve(root)
    result: list[PipelineFinding] = []
    for path in projection_paths(root):
        if not path.is_file():
            result.append(PipelineFinding(path, "required projection is missing"))
            continue
        if path.name == "manifest.json":
            payload = json.loads(path.read_text(encoding="utf-8"))
            agents = payload.get("agents") if isinstance(payload, dict) else None
            if not isinstance(agents, dict) or any(
                not isinstance(item, dict) or item.get("model") != expected
                for item in agents.values()
            ):
                result.append(PipelineFinding(path, "manifest models drifted"))
        elif path.parent.name == "agents" and path.suffix == ".md":
            if _agent_model(path) != expected:
                result.append(PipelineFinding(path, "agent model drifted"))
        elif _yaml_model(path) != expected:
            result.append(PipelineFinding(path, "Waza model drifted"))
    for path in sorted((root / "skills").glob("*/agents/openai.yaml")):
        payload = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            result.append(
                PipelineFinding(path, "OpenAI skill metadata must be a mapping")
            )
            continue
        unsupported = sorted(set(payload) - _OPENAI_SKILL_FIELDS)
        if unsupported:
            result.append(
                PipelineFinding(
                    path,
                    f"unsupported OpenAI skill fields: {', '.join(unsupported)}",
                )
            )
    return result


def _write_yaml_model(path: Path, expected: str) -> None:
    payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise TypeError(f"{path}: expected a mapping")
    key = "defaults" if path.name == ".waza.yaml" else "config"
    config = payload.get(key)
    if not isinstance(config, dict):
        raise TypeError(f"{path}: {key} must be a mapping")
    config["model"] = expected
    path.write_text(
        yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8"
    )


def apply(root: Path) -> list[PipelineFinding]:
    """Materialize every generated model surface and remove unsupported fields."""

    changes = findings(root)
    expected = resolve(root)
    for change in changes:
        path = change.path
        if path.name == "manifest.json":
            payload = json.loads(path.read_text(encoding="utf-8"))
            for item in payload["agents"].values():
                item["model"] = expected
            path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        elif path.parent.name == "agents" and path.suffix == ".md":
            lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
            replaced = False
            for index, line in enumerate(lines[:12]):
                if line.startswith("model:"):
                    lines[index] = f"model: {expected}\n"
                    replaced = True
                    break
            if not replaced:
                if not lines or lines[0].strip() != "---":
                    raise ValueError(f"{path}: agent frontmatter is missing")
                marker = next(
                    (
                        index
                        for index, line in enumerate(lines[1:12], 1)
                        if line.strip() == "---"
                    ),
                    None,
                )
                if marker is None:
                    raise ValueError(f"{path}: agent frontmatter is unterminated")
                lines.insert(marker, f"model: {expected}\n")
            path.write_text("".join(lines), encoding="utf-8")
        elif path.match("*/agents/openai.yaml"):
            payload = yaml.safe_load(path.read_text(encoding="utf-8"))
            if not isinstance(payload, dict):
                raise TypeError(f"{path}: expected a mapping")
            payload = {
                key: value
                for key, value in payload.items()
                if key in _OPENAI_SKILL_FIELDS
            }
            path.write_text(
                yaml.safe_dump(payload, sort_keys=False, allow_unicode=True),
                encoding="utf-8",
            )
        else:
            _write_yaml_model(path, expected)
    return changes


def probe(root: Path) -> None:
    """Verify that the injected provider publishes the exact stable alias."""

    expected = resolve(root)
    base = os.environ.get("COPILOT_PROVIDER_BASE_URL", "").rstrip("/")
    key = os.environ.get("COPILOT_PROVIDER_API_KEY", "")
    if not base or not key:
        raise RuntimeError("provider URL and API key must be injected")
    parsed = urllib.parse.urlsplit(base)
    if (
        parsed.scheme not in {"http", "https"}
        or not parsed.hostname
        or parsed.username
        or parsed.password
        or parsed.query
        or parsed.fragment
    ):
        raise RuntimeError("provider URL must be an HTTP(S) origin and path")
    connection_type = (
        http.client.HTTPSConnection
        if parsed.scheme == "https"
        else http.client.HTTPConnection
    )
    connection = connection_type(parsed.hostname, parsed.port, timeout=10)
    try:
        path = f"{parsed.path.rstrip('/')}/models"
        connection.request("GET", path, headers={"Authorization": f"Bearer {key}"})
        response = connection.getresponse()
        if response.status != 200:
            raise RuntimeError(
                f"provider model discovery returned HTTP {response.status}"
            )
        payload: Any = json.loads(response.read())
    except (OSError, http.client.HTTPException, json.JSONDecodeError) as error:
        raise RuntimeError(f"provider model discovery failed: {error}") from error
    finally:
        connection.close()
    data = payload.get("data") if isinstance(payload, dict) else None
    identifiers = (
        {item.get("id") for item in data if isinstance(item, dict)}
        if isinstance(data, list)
        else set()
    )
    if expected not in identifiers:
        raise RuntimeError(f"provider does not publish required pipeline {expected!r}")
