#!/bin/sh
# Generated by gc — do not edit. Stable entrypoint for the bundled bd
# lifecycle script; the target tracks the running binary's pack cache.
exec "/home/marlonsc/.gc/cache/repos/0a41911776c52bcf2f3939f70927254a7a5fc6576e1f29f4c7d26c613b46f060/examples/bd/assets/scripts/gc-beads-bd.sh" "$@"
