"""Render Waza's executable schema outside the semantic distribution."""

from __future__ import annotations

import os
import shutil
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, cast

import yaml
from _projection import snapshot as _snapshot

from agents_governance import GovernanceBundle, SkillRecord

if TYPE_CHECKING:
    from agents_governance.skill_evals import EvalPolicy

_OWNER_MARKER = (
    "# Generated by `make waza`; edit config/evals.json, the named "
    "suite.yaml, or .waza.yaml and rerun the root verb.\n"
)


def _mapping(value: object, context: str) -> dict[str, object]:
    if not isinstance(value, dict) or not all(isinstance(key, str) for key in value):
        raise TypeError(f"{context} must be a mapping with string keys")
    return cast(dict[str, object], value)


def _load(path: Path) -> dict[str, object]:
    if path.is_symlink() or not path.is_file():
        raise ValueError(f"projection input must be a physical file: {path}")
    return _mapping(yaml.safe_load(path.read_text(encoding="utf-8")), str(path))


def _write(path: Path, value: dict[str, object], source: str) -> None:
    rendered = yaml.safe_dump(value, allow_unicode=True, sort_keys=False)
    path.write_text(f"{_OWNER_MARKER}# Source: {source}\n{rendered}", encoding="utf-8")


def _copy_physical_tree(source: Path, destination: Path) -> None:
    for path in (source, *source.rglob("*")):
        if path.is_symlink() or not (path.is_dir() or path.is_file()):
            raise ValueError(f"projection input must be a physical tree: {path}")
    shutil.copytree(source, destination)


def _projection_config(
    repository: Path,
    destination: Path,
    skills: tuple[SkillRecord, ...],
    eval_policy: EvalPolicy,
) -> tuple[str, str]:
    source = _load(repository / ".waza.yaml")
    defaults = _mapping(source.get("defaults"), ".waza.yaml defaults")
    if frozenset(defaults) != {"engine", "model"}:
        raise ValueError(".waza.yaml defaults must contain only engine and model")
    engine = defaults["engine"]
    model = defaults["model"]
    if not isinstance(engine, str) or engine != "copilot-sdk":
        raise ValueError(".waza.yaml defaults.engine must select the real copilot-sdk")
    if not isinstance(model, str) or not model.strip() or model == "auto":
        raise ValueError(".waza.yaml defaults.model must name one concrete model")
    paths = _mapping(source.get("paths"), ".waza.yaml paths")
    paths["skills"] = "skills"
    paths["evals"] = "evals"
    paths["results"] = "results"
    source["paths"] = paths
    tokens = _mapping(source.get("tokens"), ".waza.yaml tokens")
    limits = _mapping(tokens.get("limits"), ".waza.yaml tokens.limits")
    overrides = _mapping(limits.get("overrides"), ".waza.yaml tokens.limits.overrides")
    policy = _load(repository / "config" / "skills.json")
    budgets = _mapping(policy.get("budgets"), "config/skills.json budgets")
    for skill in skills:
        budget_key = f"{skill.usage.replace('-', '_')}_tokens"
        budget = budgets.get(budget_key)
        if type(budget) is not int or budget <= 0:
            raise TypeError(f"config/skills.json budgets.{budget_key} must be positive")
        relative = (skill.directory / "SKILL.md").relative_to(repository).as_posix()
        overrides[relative] = budget
    limits["overrides"] = overrides
    tokens["limits"] = limits
    source["tokens"] = tokens
    source["files"] = {
        "evalFile": "eval.yaml",
        "taskGlob": eval_policy.task_glob,
        "taskFileSuffix": eval_policy.task_suffix,
    }
    source["cache"] = {"enabled": False, "dir": "cache"}
    _write(destination / ".waza.yaml", source, ".waza.yaml")
    return engine, model


def _eval_projection(
    source: Path,
    destination: Path,
    engine: str,
    model: str,
    eval_policy: EvalPolicy,
    skill: SkillRecord,
) -> None:
    semantic = _load(source)
    execution = eval_policy.execution
    relative_skill = skill.directory.relative_to(source.parents[2])
    config: dict[str, object] = {
        "trials_per_task": execution.trials_per_task,
        "timeout_seconds": execution.timeout_seconds,
        "parallel": execution.parallel,
        "fail_fast": execution.fail_fast,
        "max_attempts": execution.retry_attempts + 1,
        "executor": engine,
        "model": model,
        "skill_directories": [(Path("../..") / relative_skill).as_posix()],
        "required_skills": [skill.name],
    }
    metric = eval_policy.metric
    behavior = eval_policy.behavior_grader
    projection: dict[str, object] = {
        "name": f"{skill.name}-eval",
        "description": semantic["description"],
        "skill": skill.name,
        "schemaVersion": eval_policy.waza_schema_version,
        "version": semantic.get("version", eval_policy.default_suite_version),
        "config": config,
        "metrics": [
            {
                "name": metric.name,
                "weight": metric.weight,
                "threshold": metric.threshold,
                "description": metric.description,
            }
        ],
        "graders": [
            {
                "type": "prompt",
                "name": f"{skill.name}-contract",
                "config": {"prompt": semantic["prompt"]},
            },
            {
                "type": behavior.type,
                "name": behavior.name,
                "config": {"max_duration_ms": behavior.max_duration_ms},
            },
        ],
        "tasks": [eval_policy.task_glob],
    }
    _write(destination, projection, str(source.relative_to(source.parents[2])))


def _copy_suite(
    source: Path,
    destination: Path,
    engine: str,
    model: str,
    eval_policy: EvalPolicy,
    skill: SkillRecord,
) -> None:
    _copy_physical_tree(source, destination)
    (destination / "suite.yaml").unlink()
    _eval_projection(
        source / "suite.yaml",
        destination / "eval.yaml",
        engine,
        model,
        eval_policy,
        skill,
    )


def _build(repository: Path, destination: Path) -> None:
    (destination / ".generated-owner").write_text(
        "Generated by `make waza` from config/evals.json, skills/, "
        "evals/*/suite.yaml, and .waza.yaml; edit those owners and rerun the "
        "root verb.\n",
        encoding="utf-8",
    )
    bundle = GovernanceBundle.load(repository)
    _copy_physical_tree(repository / "skills", destination / "skills")
    evals = destination / "evals"
    evals.mkdir()
    eval_policy = bundle.eval_policy
    engine, model = _projection_config(
        repository, destination, bundle.skills, eval_policy
    )
    skills = {skill.name: skill for skill in bundle.skills}
    for suite in sorted((repository / "evals").iterdir(), key=lambda path: path.name):
        if suite.is_symlink() or not suite.is_dir():
            raise ValueError(f"semantic suite must be a physical directory: {suite}")
        skill = skills.get(suite.name)
        if skill is None:
            raise ValueError(f"semantic suite has no skill owner: {suite}")
        _copy_suite(suite, evals / suite.name, engine, model, eval_policy, skill)


def main() -> None:
    repository = Path(__file__).resolve().parents[1]
    configured = os.environ.get("WAZA_PROJECTION_ROOT")
    if configured is None:
        raise ValueError("WAZA_PROJECTION_ROOT is required")
    raw_target = Path(configured)
    if not raw_target.is_absolute() or raw_target.is_relative_to(repository):
        raise ValueError("WAZA_PROJECTION_ROOT must be an absolute external path")
    if raw_target.name != "waza-projection":
        raise ValueError(f"refusing unexpected Waza projection root: {raw_target}")
    for ancestor in (raw_target, *raw_target.parents):
        if ancestor.exists() and ancestor.is_symlink():
            raise ValueError(f"Waza projection ancestry must be physical: {ancestor}")
    if raw_target.exists():
        raise ValueError(f"Waza projection root must not pre-exist: {raw_target}")
    target = raw_target.resolve()
    target.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    with (
        tempfile.TemporaryDirectory(
            prefix=".waza-first-", dir=target.parent
        ) as first_name,
        tempfile.TemporaryDirectory(
            prefix=".waza-second-", dir=target.parent
        ) as second_name,
    ):
        first = Path(first_name)
        second = Path(second_name)
        _build(repository, first)
        _build(repository, second)
        if _snapshot(first) != _snapshot(second):
            raise ValueError("Waza projection is not a generation fixed point")
        first.replace(target)
    print("Waza projection fixed point: 2 identical generations")


if __name__ == "__main__":
    main()
