"""Render Waza's executable schema outside the semantic distribution."""

from __future__ import annotations

import hashlib
import os
import shutil
import tempfile
from pathlib import Path
from typing import cast

import yaml
from agents_governance import GovernanceBundle

_OWNER_MARKER = (
    "# Generated by `make waza APPLY=Y`; edit the named suite.yaml or "
    ".waza.yaml and rerun the root verb.\n"
)
_SEMANTIC_CONFIG_FIELDS = frozenset(
    {
        "fail_fast",
        "parallel",
        "required_skills",
        "retry_attempts",
        "skill_directories",
        "timeout_seconds",
        "trials_per_task",
    }
)


def _mapping(value: object, context: str) -> dict[str, object]:
    if not isinstance(value, dict) or not all(isinstance(key, str) for key in value):
        raise TypeError(f"{context} must be a mapping with string keys")
    return cast(dict[str, object], value)


def _load(path: Path) -> dict[str, object]:
    if path.is_symlink() or not path.is_file():
        raise ValueError(f"projection input must be a physical file: {path}")
    return _mapping(yaml.safe_load(path.read_text(encoding="utf-8")), str(path))


def _write(path: Path, value: dict[str, object], source: str) -> None:
    rendered = yaml.safe_dump(value, allow_unicode=True, sort_keys=False)
    path.write_text(f"{_OWNER_MARKER}# Source: {source}\n{rendered}", encoding="utf-8")


def _copy_physical_tree(source: Path, destination: Path) -> None:
    for path in (source, *source.rglob("*")):
        if path.is_symlink() or not (path.is_dir() or path.is_file()):
            raise ValueError(f"projection input must be a physical tree: {path}")
    shutil.copytree(source, destination)


def _projection_config(repository: Path, destination: Path) -> tuple[str, str]:
    source = _load(repository / ".waza.yaml")
    defaults = _mapping(source.get("defaults"), ".waza.yaml defaults")
    if frozenset(defaults) != {"engine", "model"}:
        raise ValueError(".waza.yaml defaults must contain only engine and model")
    engine = defaults["engine"]
    model = defaults["model"]
    if not isinstance(engine, str) or engine != "copilot-sdk":
        raise ValueError(".waza.yaml defaults.engine must select the real copilot-sdk")
    if not isinstance(model, str) or not model.strip() or model == "auto":
        raise ValueError(".waza.yaml defaults.model must name one concrete model")
    paths = _mapping(source.get("paths"), ".waza.yaml paths")
    paths["skills"] = "skills"
    paths["evals"] = "evals"
    paths["results"] = "results"
    source["paths"] = paths
    tokens = _mapping(source.get("tokens"), ".waza.yaml tokens")
    limits = _mapping(tokens.get("limits"), ".waza.yaml tokens.limits")
    overrides = _mapping(limits.get("overrides"), ".waza.yaml tokens.limits.overrides")
    policy = _load(repository / "config" / "skills.json")
    budgets = _mapping(policy.get("budgets"), "config/skills.json budgets")
    for skill in GovernanceBundle.load(repository).skills:
        budget_key = f"{skill.usage.replace('-', '_')}_tokens"
        budget = budgets.get(budget_key)
        if type(budget) is not int or budget <= 0:
            raise TypeError(f"config/skills.json budgets.{budget_key} must be positive")
        relative = (skill.directory / "SKILL.md").relative_to(repository).as_posix()
        overrides[relative] = budget
    limits["overrides"] = overrides
    tokens["limits"] = limits
    source["tokens"] = tokens
    source["files"] = {
        "evalFile": "eval.yaml",
        "taskGlob": "tasks/*.yaml",
        "taskFileSuffix": ".yaml",
    }
    source["cache"] = {"enabled": False, "dir": "cache"}
    _write(destination / ".waza.yaml", source, ".waza.yaml")
    return engine, model


def _eval_projection(source: Path, destination: Path, engine: str, model: str) -> None:
    semantic = _load(source)
    schema_version = semantic.pop("schema_version", None)
    if schema_version != 1:
        raise ValueError(f"{source}: schema_version must equal 1")
    semantic["schemaVersion"] = "1.2"
    config = _mapping(semantic.get("config"), f"{source}: config")
    if frozenset(config) != _SEMANTIC_CONFIG_FIELDS:
        raise ValueError(f"{source}: semantic config fields are not canonical")
    retry_attempts = config.pop("retry_attempts")
    if retry_attempts != 0:
        raise ValueError(f"{source}: retry_attempts must equal zero")
    config["max_attempts"] = 1
    config["executor"] = engine
    config["model"] = model
    skill_directories = config["skill_directories"]
    if (
        not isinstance(skill_directories, list)
        or len(skill_directories) != 1
        or not isinstance(skill_directories[0], str)
    ):
        raise TypeError(f"{source}: skill_directories must contain one path")
    semantic["config"] = config
    _write(destination, semantic, str(source.relative_to(source.parents[2])))


def _copy_suite(source: Path, destination: Path, engine: str, model: str) -> None:
    _copy_physical_tree(source, destination)
    (destination / "suite.yaml").unlink()
    _eval_projection(source / "suite.yaml", destination / "eval.yaml", engine, model)


def _build(repository: Path, destination: Path) -> None:
    (destination / ".generated-owner").write_text(
        "Generated by `make waza APPLY=Y` from skills/, evals/*/suite.yaml, "
        "and .waza.yaml; edit those owners and rerun the root verb.\n",
        encoding="utf-8",
    )
    _copy_physical_tree(repository / "skills", destination / "skills")
    evals = destination / "evals"
    evals.mkdir()
    engine, model = _projection_config(repository, destination)
    for suite in sorted((repository / "evals").iterdir(), key=lambda path: path.name):
        if suite.is_symlink() or not suite.is_dir():
            raise ValueError(f"semantic suite must be a physical directory: {suite}")
        _copy_suite(suite, evals / suite.name, engine, model)


def _snapshot(root: Path) -> tuple[tuple[str, str], ...]:
    entries: list[tuple[str, str]] = []
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root).as_posix()
        if path.is_symlink() or not (path.is_dir() or path.is_file()):
            raise ValueError(f"projection contains a non-physical path: {path}")
        digest = (
            "directory"
            if path.is_dir()
            else hashlib.sha256(path.read_bytes()).hexdigest()
        )
        entries.append((relative, digest))
    return tuple(entries)


def main() -> None:
    repository = Path(__file__).resolve().parents[1]
    configured = os.environ.get("WAZA_PROJECTION_ROOT")
    if configured is None:
        raise ValueError("WAZA_PROJECTION_ROOT is required")
    target = Path(configured).resolve()
    if target.name != "waza-projection" or target.parent.name != "agents-governance":
        raise ValueError(f"refusing unexpected Waza projection root: {target}")
    if target.is_symlink() or (target.exists() and not target.is_dir()):
        raise ValueError(f"Waza projection root must be a physical directory: {target}")
    target.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    with (
        tempfile.TemporaryDirectory(
            prefix=".waza-first-", dir=target.parent
        ) as first_name,
        tempfile.TemporaryDirectory(
            prefix=".waza-second-", dir=target.parent
        ) as second_name,
    ):
        first = Path(first_name)
        second = Path(second_name)
        _build(repository, first)
        _build(repository, second)
        if _snapshot(first) != _snapshot(second):
            raise ValueError("Waza projection is not a generation fixed point")
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(first, target)
    print("Waza projection fixed point: 2 identical generations")


if __name__ == "__main__":
    main()
