"""Render the AI Hub managed project surface from the semantic governance bundle.

Reads ``config/workspaces.yaml``, loads :class:`GovernanceBundle`, and projects
skills, agents, rules, and commands into the declared workspace paths. Each
rendered file carries a ``managed-by`` marker and the bundle distribution
version in its frontmatter. Consumer surfaces declare ``retire_globs`` for
legacy artifacts that the projection sweeps on every generation.

Follows the same fixed-point generation pattern as ``render_waza_projection.py``:
two independent generations are compared by snapshot, and the result is
atomically copied into place only when both agree.
"""

from __future__ import annotations

import shutil
import tempfile
from pathlib import Path, PurePosixPath
from typing import cast

import yaml
from _projection import snapshot as _snapshot

from agents_governance import GovernanceBundle, SkillRecord

_MANAGED_BY = "agents-governance"
_GENERATED_OWNER = ".generated-owner"
_GENERATED_OWNER_NOTE = (
    "Generated by `make propagate` from config/workspaces.yaml and the "
    "semantic governance bundle; edit those owners and rerun the root verb.\n"
)
_FRONTMATTER_DELIMITER = "---\n"


def _load_config(repository: Path) -> dict[str, object]:
    config_path = repository / "config" / "workspaces.yaml"
    if config_path.is_symlink() or not config_path.is_file():
        raise ValueError(f"workspace config must be a physical file: {config_path}")
    raw = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict) or not all(isinstance(k, str) for k in raw):
        raise TypeError(f"{config_path}: must be a mapping with string keys")
    return raw  # type: ignore[return-value]


def _validate_retire_glob(value: str, context: str) -> None:
    if value != value.strip() or not value:
        raise ValueError(f"{context}: retire glob must be a non-empty trimmed string")
    if (
        value.startswith(("/", "~"))
        or "\\" in value
        or "//" in value
        or "\x00" in value
    ):
        raise ValueError(
            f"{context}: retire glob must remain repository-local: {value!r}"
        )
    if any(part in {"", ".", ".."} for part in PurePosixPath(value).parts):
        raise ValueError(f"{context}: retire glob must not escape project: {value!r}")


def _validate_config(config: dict[str, object], path: Path) -> list[dict[str, object]]:
    if config.get("version") != 1:
        raise ValueError(f"{path}: version must be 1")
    workspaces = config.get("workspaces")
    if not isinstance(workspaces, list) or not workspaces:
        raise ValueError(f"{path}: workspaces must be a non-empty list")
    for idx, ws in enumerate(workspaces):
        if not isinstance(ws, dict):
            raise TypeError(f"{path}: workspace[{idx}] must be a mapping")
        ctx = f"{path}: workspace[{idx}]"
        if not isinstance(ws.get("name"), str) or not ws["name"]:
            raise ValueError(f"{ctx}.name is required")
        if not isinstance(ws.get("path"), str) or not ws["path"]:
            raise ValueError(f"{ctx}.path is required")
        if ws["path"].startswith("/") or ".." in Path(ws["path"]).parts:
            raise ValueError(f"{ctx}.path must be relative: {ws['path']!r}")
        subjects = ws.get("subjects")
        if not isinstance(subjects, list) or not all(
            isinstance(s, str) and s for s in subjects
        ):
            raise ValueError(f"{ctx}.subjects must be a non-empty list of strings")
        globs = ws.get("retire_globs")
        if not isinstance(globs, list) or not all(isinstance(g, str) for g in globs):
            raise ValueError(f"{ctx}.retire_globs must be a list of strings")
        for glob in globs:
            _validate_retire_glob(glob, f"{ctx}.retire_globs")
    return list(workspaces)  # type: ignore[return-value]


def _inject_managed_marker(text: str, version: str) -> str:
    """Inject managed-by and managed-version into YAML frontmatter.

    Canonical sources never carry the marker: the projector injects it at
    render time. A projected file lacking the marker, or holding a foreign
    or older version, is swept by ``retire_globs`` on the next publish.
    """

    if not text.startswith(_FRONTMATTER_DELIMITER):
        return text
    end_idx = text.find("\n" + _FRONTMATTER_DELIMITER, 4)
    if end_idx < 0:
        return text
    frontmatter = text[4 : end_idx + 1]
    body = text[end_idx + 1 + len(_FRONTMATTER_DELIMITER) :]
    lines = [
        line
        for line in frontmatter.rstrip("\n").split("\n")
        if not line.startswith("managed-by:")
        and not line.startswith("managed-version:")
    ]
    lines.insert(0, f"managed-by: {_MANAGED_BY}")
    lines.insert(1, f"managed-version: {version}")
    return f"{_FRONTMATTER_DELIMITER}{'\n'.join(lines)}\n{_FRONTMATTER_DELIMITER}{body}"


def _copy_managed_file(source: Path, dest: Path, version: str) -> None:
    text = source.read_text(encoding="utf-8")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(_inject_managed_marker(text, version), encoding="utf-8")


def _copy_managed_tree(source: Path, dest: Path, version: str) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    for path in sorted(source.rglob("*")):
        if path.is_dir():
            continue
        if path.is_symlink() or not path.is_file():
            raise ValueError(f"projection source must be physical: {path}")
        relative = path.relative_to(source)
        target = dest / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        if path.suffix == ".md":
            _copy_managed_file(path, target, version)
        else:
            shutil.copy2(path, target)


def _project_agents(bundle: GovernanceBundle, dest: Path, version: str) -> None:
    for agent in bundle.agents:
        rel = Path(agent.distribution) / agent.path.name
        _copy_managed_file(agent.path, dest / "agents" / rel, version)


def _project_rules(bundle: GovernanceBundle, dest: Path, version: str) -> None:
    for rule in bundle.rules:
        if "route:personal" in rule.tags:
            continue
        rel = PurePosixPath(rule.identity).parent
        _copy_managed_file(rule.path, dest / "rules" / rel / rule.path.name, version)


def _project_commands(bundle: GovernanceBundle, dest: Path, version: str) -> None:
    for command in bundle.commands:
        if command.route.value == "agent":
            continue
        rel = PurePosixPath(command.path.relative_to(bundle.root / "commands")).parent
        _copy_managed_file(
            command.path, dest / "commands" / rel / command.path.name, version
        )


def _skill_subjects_match(skill: SkillRecord, subjects: frozenset[str]) -> bool:
    if not skill.subjects:
        return True
    return bool(frozenset(skill.subjects) & subjects)


def _project_skills(
    bundle: GovernanceBundle,
    dest: Path,
    version: str,
    subjects: list[str],
) -> None:
    subject_set = frozenset(subjects)
    for skill in bundle.skills:
        if skill.category.conditional:
            if not _skill_subjects_match(skill, subject_set):
                continue
            if "project" not in skill.routes:
                continue
            if skill.activation == "opt-in":
                continue
        rel = skill.directory.relative_to(bundle.root / "skills")
        _copy_managed_tree(skill.directory, dest / "skills" / rel, version)


def _apply_retire_globs(target: Path, globs: list[str]) -> None:
    for glob in globs:
        for path in target.glob(glob):
            if path.is_file():
                path.unlink()
            elif path.is_dir():
                shutil.rmtree(path)


def _build(
    bundle: GovernanceBundle,
    dest: Path,
    subjects: list[str],
) -> None:
    version = bundle.distribution_version
    (dest / _GENERATED_OWNER).write_text(
        f"{_GENERATED_OWNER_NOTE}managed-by: {_MANAGED_BY}\n"
        f"managed-version: {version}\n",
        encoding="utf-8",
    )
    _project_agents(bundle, dest, version)
    _project_rules(bundle, dest, version)
    _project_commands(bundle, dest, version)
    _project_skills(bundle, dest, version, subjects)


def _build_workspace(repository: Path, workspace: dict[str, object]) -> None:
    name = cast(str, workspace["name"])
    workspace_path = cast(str, workspace["path"])
    subjects = cast(list[str], workspace["subjects"])
    retire_globs = cast(list[str], workspace["retire_globs"])
    target = repository / workspace_path
    print(
        f"propagate · {name} -> {target}\n"
        f"subjects: {', '.join(subjects)}\n"
        f"retire_globs: {retire_globs}",
        flush=True,
    )
    bundle = GovernanceBundle.load(repository)
    target.parent.mkdir(parents=True, exist_ok=True)
    with (
        tempfile.TemporaryDirectory(
            prefix=".project-first-", dir=str(target.parent)
        ) as first,
        tempfile.TemporaryDirectory(
            prefix=".project-second-", dir=str(target.parent)
        ) as second,
    ):
        first_path = Path(first)
        second_path = Path(second)
        _build(bundle, first_path, subjects)
        _build(bundle, second_path, subjects)
        if _snapshot(first_path) != _snapshot(second_path):
            raise ValueError(
                f"project projection for {name} is not a generation fixed point"
            )
        if target.exists():
            _apply_retire_globs(target, retire_globs)
            shutil.rmtree(target)
        shutil.copytree(first_path, target)
    print(f"propagate · {name}: fixed point verified", flush=True)


def main() -> None:
    repository = Path(__file__).resolve().parents[1]
    config = _load_config(repository)
    workspaces = _validate_config(config, repository / "config" / "workspaces.yaml")
    for workspace in workspaces:
        _build_workspace(repository, workspace)


if __name__ == "__main__":
    main()
