"""Project the governance capsule into every provider surface.

This tool is the single writable authority for generated hook scripts, the
OpenCode governance plugin, and instruction-pointer files (CLAUDE.md,
GEMINI.md). It composes the capsule from the validated ``GovernanceBundle``
and embeds it deterministically into each provider's delivery mechanism.

Run via ``make gen``. The tool validates fixed-point idempotence by generating
twice and comparing a content-addressed snapshot.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from _projection import snapshot as _snapshot
from agents_governance import GovernanceBundle
from agents_governance.capsule import Capsule, render_capsule
from agents_governance.capsule import CAPSULE_MARKER, OPCODE_MARKER

_HOOK_TEMPLATE = """\
#!/usr/bin/env python3
import json
import sys

payload = json.load(sys.stdin)
if not isinstance(payload, dict):
    raise TypeError('hook input must be a JSON object')
response = json.loads({literal})
json.dump(response, sys.stdout, ensure_ascii=False, separators=(',', ':'))
sys.stdout.write('\\n')
"""

_OPCODE_TEMPLATE = """\
// AUTO-GENERATED by `make gen` — edit canonical sources only.
const CAPSULE = __CAPSULE_LITERAL__;
const DIGEST = "__DIGEST__";

export const AiHubGovernance = async () => ({
  "experimental.chat.system.transform": async (_input, output) => {
    const block = `<!-- __MARKER__ ${DIGEST} -->\\n${CAPSULE}`;
    if (!output.system.some((entry) => entry.includes(DIGEST))) {
      if (output.system.length === 0) output.system.push(block);
      else output.system[0] = `${output.system[0]}\\n\\n${block}`;
    }
  },
  "experimental.session.compacting": async (_input, output) => {
    if (!output.context.some((entry) => entry.includes(DIGEST))) {
      output.context.push(`<!-- __MARKER__ ${DIGEST} -->\\n${CAPSULE}`);
    }
  },
});
"""

_INSTRUCTION_TEMPLATE = """\
<!-- @generated by ai-hub from config/governance.json; regenerate with `make gen`. -->
# __FILENAME__

Read [`AGENTS.md`](AGENTS.md) before acting. It is the sole project instruction authority.

<!-- AIHUB-INSTRUCTION-POINTER -->
"""

_FILE_MODE = 0o755
_JSON_MODE = 0o644


@dataclass(frozen=True)
class HookDef:
    provider: str
    relpath: str
    response_factory: Callable[[str], dict[str, object]]


_HOOKS: tuple[HookDef, ...] = (
    HookDef("codex", ".codex/aihub-hooks/codex-sessionstart.py",
            lambda c: {"hookSpecificOutput": {"hookEventName": "SessionStart",
                                              "additionalContext": c}}),
    HookDef("codex", ".codex/aihub-hooks/codex-subagentstart.py",
            lambda c: {"hookSpecificOutput": {"hookEventName": "SubagentStart",
                                              "additionalContext": c}}),
    HookDef("codex", ".codex/aihub-hooks/codex-userpromptsubmit.py",
            lambda c: {"hookSpecificOutput": {"hookEventName": "UserPromptSubmit",
                                              "additionalContext": c}}),
    HookDef("gemini", ".gemini/aihub-hooks/gemini-sessionstart.py",
            lambda c: {"hookSpecificOutput": {"hookEventName": "SessionStart",
                                              "additionalContext": c}}),
    HookDef("gemini", ".gemini/aihub-hooks/gemini-beforeagent.py",
            lambda c: {"hookSpecificOutput": {"hookEventName": "BeforeAgent",
                                              "additionalContext": c}}),
    HookDef("gemini", ".gemini/aihub-hooks/gemini-precompress.py",
            lambda _c: {}),
    HookDef("cursor", ".cursor/aihub-hooks/cursor-sessionstart.py",
            lambda c: {"additional_context": c}),
    HookDef("cursor", ".cursor/aihub-hooks/cursor-beforesubmitprompt.py",
            lambda _c: {"continue": True}),
    HookDef("cursor", ".cursor/aihub-hooks/cursor-precompact.py",
            lambda _c: {}),
    HookDef("cursor", ".cursor/aihub-hooks/cursor-subagentstart.py",
            lambda _c: {"permission": "allow"}),
)


def _render_python_hook(response: dict[str, object]) -> str:
    json_str = json.dumps(response, ensure_ascii=False, separators=(",", ":"))
    literal = repr(json_str)
    return _HOOK_TEMPLATE.format(literal=literal)


def _render_opencode_plugin(capsule: Capsule) -> str:
    capsule_literal = json.dumps(capsule.text, ensure_ascii=False)
    return (
        _OPCODE_TEMPLATE
        .replace("__CAPSULE_LITERAL__", capsule_literal)
        .replace("__DIGEST__", capsule.opencode_digest)
        .replace("__MARKER__", OPCODE_MARKER)
    )


def _render_instruction_pointer(filename: str) -> str:
    return _INSTRUCTION_TEMPLATE.replace("__FILENAME__", filename)


def _write_file(path: Path, content: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(mode)


def _update_manifest(
    manifest_path: Path, generated: dict[str, tuple[str, str]]
) -> None:
    """Update the ``managed`` section of a manifest with new file digests."""
    if manifest_path.is_file():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    else:
        manifest = {"managed": {}}
    managed = manifest.get("managed", {})
    for relpath, (digest, file_mode) in generated.items():
        managed[relpath] = {"digest": digest, "mode": file_mode}
    manifest["managed"] = managed
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _manifest_path(provider: str) -> Path:
    mapping = {
        "codex": Path(".codex/.hooks.json.agents-governance.json"),
        "gemini": Path(".gemini/.settings.json.agents-governance.json"),
        "cursor": Path(".cursor/.hooks.json.agents-governance.json"),
    }
    return mapping[provider]


def _build_hooks(root: Path, capsule: Capsule) -> None:
    capsule_text = capsule.text
    by_provider: dict[str, dict[str, tuple[str, str]]] = {}
    for hook in _HOOKS:
        full = root / hook.relpath
        response = hook.response_factory(capsule_text)
        content = _render_python_hook(response)
        digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
        _write_file(full, content, _FILE_MODE)
        by_provider.setdefault(hook.provider, {})[hook.relpath] = (digest, "0755")
    for provider, generated in by_provider.items():
        _update_manifest(root / _manifest_path(provider), generated)


def _build_opencode(root: Path, capsule: Capsule) -> None:
    relpath = ".opencode/plugins/aihub-governance.ts"
    full = root / relpath
    content = _render_opencode_plugin(capsule)
    digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
    _write_file(full, content, _JSON_MODE)
    manifest = root / ".opencode/plugins/.aihub-governance.ts.agents-governance.json"
    _update_manifest(manifest, {relpath: (digest, "0644")})


def _build_instructions(root: Path) -> None:
    for name in ("CLAUDE.md", "GEMINI.md"):
        _write_file(root / name, _render_instruction_pointer(name), _JSON_MODE)


def _build(root: Path, capsule: Capsule) -> None:
    _build_hooks(root, capsule)
    _build_opencode(root, capsule)
    _build_instructions(root)


def project(root: Path, capsule: Capsule) -> None:
    """Generate all provider surfaces and validate fixed-point idempotence."""
    first = Path(tempfile.mkdtemp(prefix=".gen-first-", dir=root))
    second = Path(tempfile.mkdtemp(prefix=".gen-second-", dir=root))
    try:
        _build(first, capsule)
        _build(second, capsule)
        if _snapshot(first) != _snapshot(second):
            raise ValueError("governance projection is not a generation fixed point")
    finally:
        shutil.rmtree(first, ignore_errors=True)
        shutil.rmtree(second, ignore_errors=True)
    _build(root, capsule)
    print(f"Governance projection fixed point: {len(_HOOKS)} hooks + 1 plugin + 2 pointers")


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    bundle = GovernanceBundle.load(root)
    capsule = render_capsule(bundle)
    project(root, capsule)


if __name__ == "__main__":
    main()
